spring.application.name=smt
server.port=8090

## Data Base ###
# Database URL
spring.datasource.url=jdbc:sqlserver://AASMAN:1433;encrypt=true;databaseName=AVIRATTECH;TrustServerCertificate=true

# DB Credentials
spring.datasource.username=naresh2
spring.datasource.password=121121

# Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=create

# Show SQL (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true